##########################################################################
# This file contains the definition of the K8s namespaces and             #
# service accounts ManageIQ needs to be defined in a K8s cluster          #    
# to be able to set up a K8s provider that manages that cluster.          #
# It was written using the instructions at                                #
# http://manageiq.org/docs/guides/providers/kubernetes as a guide.        #
# Notice how at that link everything is done imperatively (i.e.           #
# "kubectl create ...") and object configs are specificed as CLI args.    # 
# This file is the "translation" of those configs of K8s objects          #
# to a .yaml config file, and it's meant to be used with "kubectl apply". #
##########################################################################

---

apiVersion: v1
kind: Namespace
metadata: 
  annotations: 
    ns-config-copied-from: http://manageiq.org/docs/guides/providers/kubernetes
  name: management-infra

---

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    sa-config-copied-from: http://manageiq.org/docs/guides/providers/kubernetes
  name: management-admin
  namespace: management-infra

---

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    sa-config-copied-from: http://manageiq.org/docs/guides/providers/kubernetes
  name: inspector-admin
  namespace: management-infra

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: cluster-reader
  annotations:
    copied-from-url: https://docs.openshift.com/container-platform/3.9/admin_guide/manage_rbac.html
    copied-from-openshift-v: 3.9
rules:
- apiGroups: ["apiregistration"]
  resources: ["apiservices.apiregistration.k8s.io", "apiservices.apiregistration.k8s.io/status", "appliedclusterresourcequotas"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["*"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: management-infra-cluster-reader
  annotations: 
    binding-config-copied-from: http://manageiq.org/docs/guides/providers/kubernetes
subjects:
- kind: User
  name: system:serviceaccount:management-infra:management-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io

---