######################################################
# This file defines handler, instance (quota), rule,
# QuotaSpec and QuotaSpecBinding to enable rate limiting
# to access the service productpage based on source IP. 
######################################################
apiVersion: config.istio.io/v1alpha2
kind: memquota
metadata:
  name: rate-limit
  namespace: istio-system
spec:
  quotas:
  - name: src-ip-dest-svc.quota.istio-system
    # Such a low rate is used because the project this config belongs to is a demo:
    # we want a human user using the productpage app to notice that the rate limit
    # is enforced
    maxAmount: 1
    validDuration: 10s  

---

apiVersion: config.istio.io/v1alpha2
kind: quota
metadata:
  name: src-ip-dest-svc
  namespace: istio-system
spec:
  dimensions:
    originIP: origin.ip | ip(request.headers["x-forwarded-for"]) | ip("0.0.0.0")
    destinationService: destination.service | "unknown"

---

apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: limiter
  namespace: istio-system
spec:
  actions:
  - handler: rate-limit.memquota
    instances: 
    - src-ip-dest-svc.quota   

---

apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: count-by-one
  namespace: istio-system
spec:
  rules:
  - quotas:
    - charge: 1
      quota: src-ip-dest-svc

---

apiVersion: config.istio.io/v1alpha2
kind: QuotaSpecBinding
metadata:
  name: count-by-one-productpage
  namespace: istio-system
spec:
  quotaSpecs:
  - name: count-by-one
    namespace: istio-system
  services:
  - name: productpage
    namespace: molivi-dev
